apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.service.group: trex
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex
    app.kubernetes.io/part-of: rh-trex
    io.kompose.service: trex
  name: rh-trex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex
      io.kompose.service: trex
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.service.expose: "true"
        kompose.service.group: trex
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex
        io.kompose.network/rh-trex-default: "true"
        io.kompose.service: trex
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: rhtrex
        - name: POSTGRESQL_PASSWORD
          value: foobar-bizz-buzz
        - name: POSTGRESQL_USER
          value: trex
        image: quay.io/sclorg/postgresql-15-c8s:latest
        livenessProbe:
          exec:
            command:
            - pg_isready
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: trex-db
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
      - args:
        - |
          /rh-trex/trex migrate
          /rh-trex/trex serve --api-server-bindaddress=0.0.0.0:8000
        command:
        - sh
        - -c
        image: trex
        name: trex
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
